on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    if: github.ref == 'refs/heads/main'
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_html/
        protocol: sftp
        port: 22
        timeout: 300000